### ISSUE TITLE
font size problems

### ISSUE THREAD

**Issue by mojoaxel** [unify/unify#73]
There seams to be a problem with the "fontSize" value in the appearance.
Relative values like "medium" or "large" are recognized correctly while absolute values like "19px" seamed to be ignored.

The following code is **not** working. There is always a fontsize of 16px set.

``` javascript
var style = {
    fontSize: "19px"
};
```

The following examples are working like expected:

``` javascript
var style = {
    font: "19px"
};
```

``` javascript
var style = {
    fontSize: "large"
};
```

**Comment by dominikg** [comment]
quickfix: use fontSize:19 and it works.

The problem is, that fontSize values with typeof string are all passed to unify.bom.Font#resolveRelativeSize in unify.ui.core.Widget#1402. 

If you want to be able to pass in string values with px, you'd have to update line 1402 of widget like this:
```if (typeof(fontSize) == "string" && fontSize.substr(-2)!="px") {

```

or change unify.bom.Font#resolveRelativeSize to check for "px"
```
